name: Python Syntax Check Using Conda

on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Check for Syntax Errors (linux, python 3.10)
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.5
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install flake8 dependency
      run: |
         conda install flake8
    - name: Lint with flake8
      run: |       
        # stop the build if there are Python syntax errors
        flake8 . -v --count --select=E9,F7 --show-source --statistics

  build-linux-name-err:
    name: Check Name and Syntax Errors (linux, python 3.10)
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.5
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file envs/zmia-env.yml --name base
        conda install flake8
    - name: Lint with flake8
      run: |        
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-complexity=10 --statistics
